# Sample .travis.yml for R projects

language: r
warnings_are_errors: true
sudo: required
r_binary_packages:
  - devtools
  - drc
  - dplyr

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'library(covr);coveralls()'

notifications:
  email:
    on_success: change
    on_failure: always


env:
  global:
    - CRAN: "http://cran.rstudio.com"
    - NOT_CRAN: true
    - R_BUILD_ARGS="--resave-data --compact-vignettes=gs+qpdf"
    - R_CHECK_ARGS="--as-cran --timings"
    - R_CHECK_TIME="TRUE"
    - R_CHECK_TESTS="TRUE"
    - _R_CHECK_TIMINGS_="0"
    - $BOOTSTRAP_LATEX="TRUE"
    - WARNINGS_ARE_ERRORS="FALSE"
